# Generated by Django 5.2.15 on 2026-06-24 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('live_url', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=500, null=True)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.IntegerField(db_index=True, default=0)),
                ('status', models.CharField(default='active', max_length=50)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('icon_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'technologies',
                'db_table': 'technologies',
            },
        ),
        migrations.CreateModel(
            name='ProjectMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=255)),
                ('metric_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='projects.project')),
            ],
            options={
                'db_table': 'project_metrics',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.technology'),
        ),
    ]
