# Generated by Django 5.2.15 on 2026-06-24 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('display_order', models.IntegerField(db_index=True, default=0)),
                ('technologies', models.ManyToManyField(blank=True, related_name='experiences', to='projects.technology')),
            ],
            options={
                'db_table': 'experience',
                'ordering': ['display_order', '-start_date'],
            },
        ),
    ]
