# Generated by Django 5.2.15 on 2026-06-24 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('icon_name', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
